apiVersion: v1
kind: Secret
metadata:
  name: ludocloud-secret
  namespace: ludocloud
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ludocloud?schema=public
  JWT_ACCESS_SECRET: dev_access_secret_change_me
  JWT_REFRESH_SECRET: dev_refresh_secret_change_me
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: ludocloud